language: java

jdk:
  - oraclejdk8
  
before_install:
  - echo "Before install"
  
install:
  - echo "Install"
  
after_install:
  - echo "After install"

before_script: 
  - cd biuxx-utils && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..
  - cd biuxx-viracct-service && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..
  
script:
  - cd biuxx-viracct && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..
  
after_success:
  - echo "Biu++ Build done!"
