language: java

jdk:
  - oraclejdk8
  
middware:
  - echo "Before install"
  
tools:
  - cd biuxx-utils && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..

interfaces: 
  - cd biuxx-viracct-service && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..
  
apps:
  - cd biuxx-viracct && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..
  
after_success:
  - echo "Biu++ Build done!"
