language: java

jdk:
  - oraclejdk8
  
before_install:
  - echo "Before install"
  - echo "Do something before build"
  
install:
  - echo "install step"

script: 
  - cd biuxx-utils && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..
  - cd biuxx-viracct-service && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..
  - cd biuxx-viracct && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..
  
after_success:
  - echo "Build done!"
