language: java

jdk:
  - oraclejdk8
  
before_install:
  - echo "Before install"
  
install:
  - echo "Install"

before_script: 
  - cd biuxx-utils && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..
  - cd biuxx-viracct-api && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..
  - cd biuxx-tranx-api && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..
  - cd biuxx-custom-api && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..
  - cd biuxx-merchant-api && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..
  - cd biuxx-user-api && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..
  - cd biuxx-clearing-api && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..
  - cd biuxx-settlement-api && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..
  
script:
  - cd biuxx-viracct && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..
  - cd biuxx-tranx && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..
  - cd biuxx-custom && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..
  - cd biuxx-merchant && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..
  - cd biuxx-user && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..
  - cd biuxx-clearing && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..
  - cd biuxx-settlement && mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true && cd ..
  
after_success:
  - echo "Biu++ Build done!"
